name: TikTokLive
version: 1.1.1-BETA
main: dev.timecoding.tiktokspawn.TikTokSpawn
api-version: 1.13
authors: [ TimeCoding ]
description: A plugin which allows to execute specific actions after a TikTok Donation was received!
website: timecoding.de

commands:
  tiktoklive:
    description: "The main command for the TikTokLive-Plugin"
    aliases:
      - ttl