name: TikTokLive
version: 1.0-BETA
main: dev.timecoding.tiktokspawn.TikTokSpawn
api-version: 1.19
authors: [ TimeCoding ]
description: A plugin which allows to execute specific actions after a TikTok Donation was received!
website: timecoding.de
